pipeline {
    agent any
    tools{
        maven 'MavenHome'
    }
    stages {
        stage('Build') { 
            steps {
                sh "cd springbootmaven_jenkins && mvn clean package"
            }
        }
    }
}