pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'export MAVEN_HOME=/Users/nsraghavan/apache-maven-3.9.9'
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}