pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'echo $M2_HOME'
                sh 'export MAVEN_HOME=$M2_HOME'
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}