pipeline {
    agent any
    tools{
        maven 'MavenHome'
        dockerTool 'DockerHome'
    }
    stages {
        stage('Build Code') { 
            steps {
                sh "cd springbootdocker_jenkins && mvn clean package"
            }
        }
        stage('Build Docker Image'){
            steps{
                sh "cd springbootdocker_jenkins/target && sudo usermod -a -G docker build -t springboot-learning:latest"
            }
        }
    }
}