pipeline {
    agent any
    tools{
        maven 'MavenHome'
        dockerTool 'DockerHome'
    }
    stages {
        stage('Build Code') { 
            steps {
                sh "cd springbootdocker_jenkins && mvn clean package"
            }
        }
        stage('Build Docker Image'){
            steps{
                sh "echo 'Printing Docker version' "
                sh "docker --version"
                sh "cd springbootdocker_jenkins/target && docker build -t springboot-learning:latest"
            }
        }
    }
}